# Generated by Django 4.0.5 on 2022-07-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_bid_user_alter_listing_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='picture',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
