# Generated by Django 4.0.5 on 2022-10-01 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='avg_response_time',
            new_name='avgresponsetime',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='total_response_time',
            new_name='totalresponsetime',
        ),
    ]
