# Generated by Django 4.0.5 on 2022-09-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='wrong',
        ),
        migrations.AlterField(
            model_name='game',
            name='right',
            field=models.BooleanField(default=False),
        ),
    ]
