# Generated by Django 4.0.5 on 2022-09-23 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mathangoapp', '0002_remove_game_wrong_alter_game_right'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=3000)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='game',
            old_name='questions',
            new_name='wrong',
        ),
        migrations.AddField(
            model_name='game',
            name='digit',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='right',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
