# Generated by Django 4.0.5 on 2022-10-01 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathangoapp', '0002_rename_avg_response_time_game_avgresponsetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='total_wrong',
        ),
    ]
