# Generated by Django 4.0.5 on 2022-10-01 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathangoapp', '0003_remove_userstats_total_wrong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='rw',
        ),
    ]
